### ISSUE TITLE
Reset button's function on Indicator Setup form not clear, can break form

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1029]
**Description:**
The reset button's function on the Indicator setup form is not clear as to its intended impact. Clicking on the reset button as a user, would expect the form to revert to it's original state. This is not the case. Also, when hitting the reset button after adding targets, the original targets remain, but the form appears to want the user to select a new target frequency, essentially breaking the form. 

**Steps to Reproduce:**
1. Login to Tola-Activity
2. Click Testing specific Program "TolaData Test"
3. Click the Gear symbol to edit an indicator Or create a new one
4. Go to targets tab and select Target Frequency, select a frequency type. 
5. Click create targets.
6. Click reset

**Results:**
Target frequency is reset, but targets remain. User cannot select a new frequency, or delete targets in modal. The real cancel/reset here comes when the user closes the modal. 

**Expected Results:**
Reset button is removed, or functions in a different way, or actually reverts the form to its original state before editing. 

**Attachments:**
![screen shot 2019-01-04 at 3 17 48 pm](https://user-images.githubusercontent.com/23220180/50716053-adb25480-1034-11e9-8584-709a81f70183.png)

**Comment by jennyhavah** [comment]
I see how this is confusing. Ideally, if you have not yet saved any target values and want to start all over, clicking Reset would restore the form to the previous stage of the process -- removing the target table and clearing the target frequency. Right now, you have to click "Remove all targets" to get back to that state.

Unfortunately, fixing this usability issue would involve a high level of effort and a high level of risk, based on what I experienced in the Winterhawks release. In fact, I am pretty sure I asked about this Reset behavior during Winterhawks, and the current approach turned out to be the best of several not-so-great options. Doing it the "right way" would involve reworking the flow of how targets get created, ensuring we account for all the variations of target frequencies (time aware vs. non time aware, etc.), ensuring we preserve all of the logic around saved targets and any existing linked results, displaying the correct warning messages when you delete targets, etc. 

I'm going to remove this from Ghost Pepper, as I don't consider the work to be low-risk or low-effort. This improvement could be a potential candidate for the FY2020 roadmap.

**Comment by jennyhavah** [comment]
Closing this ticket because we replaced the "Reset" button with a Cancel button.
