### ISSUE TITLE
Map zoom in/out buttons are overlapping the program droplist on sites page

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1059]
**Description:**
When selecting from the "Programs" drop list selector, the map's zoom in/out buttons are overlapping the program selections. 

Please see attached image.

**Steps to Reproduce:**

1. Login to Tola-Activity
2. Click Settings, change to french
3. Select Tola-Data Test program
4. Click View Program Sites on left hand side of the page 
5. Click the programs drop list. 

**Results:**
Map element is overlapping program drop list, obstructing selection

**Expected Results:**
Programs drop list is displayed over map elements. 

**Attachments:**
![map_overlay](https://user-images.githubusercontent.com/23220180/51126615-72ecb100-17d8-11e9-86ca-fac2e16dc458.png)

**Comment by RickieT** [comment]
**QA Failed:**
Where: https://tola-activity-qa.mercycorps.org/workflow/siteprofile_list/542/0/?search=1
* Considerably worse now, the programs droplist now opens on the entire screen, and displaces the site footer. 
![image](https://user-images.githubusercontent.com/23220180/53272816-259d1280-36a7-11e9-9799-e64a95493294.png)

**Comment by KennyMonster** [comment]
There's 2 separate issues here. The first is that "Leaftlet" is still hovering of the menu which I fixed in the above commit.

The 2nd is that the menu is super janky, and gets massive when the contents are massive. The right thing to do here is ripping that select component out and replacing with one we use on other pages (e.g. bootstrap-multiselect)

**Comment by RickieT** [comment]
**QA Verified:**
- [x] Leaflet no longer hovering, moving to ready for deploy
