### ISSUE TITLE
Trying to save 0 or negative values for the number of Event targets fails

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#106]
I have this test, which tries to set a number of events to 0 while still providing a name for the first event. 
```
533       it('should limit max "Number of events" to 12 or less', function() {
534         IndPage.clickIndicatorsLink();
535         TargetsTab.clickNewIndicatorButton();
536         TargetsTab.saveNewIndicator();
537 
538         TargetsTab.setIndicatorName('Can create max of 12 events initially testing');
539         TargetsTab.setUnitOfMeasure('Mangos per manager');
540         TargetsTab.setLoPTarget(538);
541         TargetsTab.setBaseline(539);
542         TargetsTab.setTargetFrequency('Event');
543         TargetsTab.setFirstEventName('Battle of Cable Street');
544         TargetsTab.setNumTargetEvents(13);
545 
546         // Should fail
547         TargetsTab.saveIndicatorChanges();
548         let errorMessage = TargetsTab.getNumTargetEventsErrorHint();
549         assert(errorMessage.includes('You can start with up to 12 targets and add more later.'));
550       });
```
I expect failure, but this succeeds, or appears to. What I actually get is a screen that looks like the following (I didn't capture the ephemeral success popup). It isn't clear from this screen, but the update fails as far as I can tell because no sign of my other changes survives. 
![targets_bug](https://user-images.githubusercontent.com/5178160/36481823-d3341428-16c5-11e8-9c3b-c90d5d07256f.png)

**Comment by mahmoodkhan** [comment]
The save operation is in fact successful; however, there if you do not specify any targets and just exit out of the modal window then next time you open the same Indicator, the system unsets the target_frequency  you had previously saved because making a user select the target frequency provides a context. The details are covered in a story from the v.1.9.3 but can't recall what story it was. @jennyhavah probably can find it or remembers it.

**Comment by kurtwall** [comment]
Oh, right. I remember this now. We talked about it before. :-) I'll close this issue.
