### ISSUE TITLE
Issues with metrics tracking and indicator target creatiopnm

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1095]
**Description:**
An issue was reported with our visual metrics tracking not tracking an indicator's targets. In production, this program is : https://tola-activity.mercycorps.org/program/584/0/0/

To resolve this issue: 
:one: Make sure no programs can continue doing this, going forward and
:two: Figure out how to handle existing programs that have mid-month start and end dates.

**Comment by RickieT** [comment]
I do think the errors shown are related to this:
https://github.com/mercycorps/TolaActivity/issues/1018

However, the main issue here is that target metrics were not tracking for this program when an indiactor was created with targets

**Comment by RickieT** [comment]
Still investigating this - @camgnostic

**Comment by camgnostic** [comment]
Errors on accessing were in fact related to #1018 @RickieT, (give yourself access to CAR in admin to avoid those 500/404 errors, and that will be fixed when 1018 goes live - you won't be able to look at a page that you can't also update indicators on)

The "not all targets defined" error was related to a different and urgent bug - the program start dates are mid-month, which our validation is supposed to prevent.  With start and end dates mid-month our "how many targets should you have" logic falls apart, both on target generation and on determining if enough targets exist.  This bug is superceded by that one, which will require both fixing validation and repairing bad data.

**Comment by camgnostic** [comment]
The two issues here are resolved - if you have access to the country you do not get 500/404 errors, and if program start/end dates are correct then the targets defined metric is correct.  
Access: #1018 
Start/end dates for programs created after now: #1111 
Start/end dates for program reporting period update: #1100 
Start/end dates for existing programs: #1109 

As all the issues in this ticket are addressed in other tickets, I'm closing it.
