### ISSUE TITLE
"no options" drop down item remains when de-selecting a program on document page

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1124]
When viewing documents from a program page, I am shown filters above a paginated list of documents. If I click filter by indicator, and de-select/remove a program filter, the drop list menu says "no options" and remains on screen. 

See attached image: 
![screen shot 2019-01-24 at 1 01 55 pm](https://user-images.githubusercontent.com/23220180/51708328-81a54600-1fd8-11e9-96f4-49355adf27ae.png)

**Steps to reproduce:**
From the home page, select a program
click "View program documents" on left navigation
Click Filter by indicator (from a program that has indicators"
click the x on the "filter by program" drop down menu

**Results:**
Drop list menu remains on screen until a program is selected with indicators

**Expected Results:**
UI element is disabled and non invasive when indicator is not an option

**Comment by KennyMonster** [comment]
I sort of fixed this, but it isn't perfect. The lack of perfection is due to a bug in the react-select widget lib itself where

If you both disable and force close a react-select widget, when the widget is re-enabled, it returns to the open/close state it was in before being disabled. This means if you click the X in the program select while the indicator select menu is visible, the indicator pulldown menu will close, but re-open again once you select another program.

If you properly close the indicator pulldown, it works as expected though. Also, if you forgo disabling the indicator select widget, force closing will keep it closed, even after a new program is selected.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Issue no longer persists as written by following original steps.
