### ISSUE TITLE
When a URL is added as evidence, expanding/constricting indicator grossly expands the indicator info to the right

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1139]
See attached media: 
![expand](https://user-images.githubusercontent.com/23220180/51936817-e805dc00-23bd-11e9-8ac7-d7464b69e3c2.gif)

**Comment by KennyMonster** [comment]
@jennyhavah Is truncation or wrapping the right thing to do in the case of long evidence URLs?

**Comment by jennyhavah** [comment]
Wrapping is preferred to truncation, because if the original attacher of evidence did not go to the trouble to name their file, the URL is all people have to work with to interpret what the file might be, before going ahead and opening it.

We could set a reasonable limit, though -- like, truncate after a few lines -- however that would work programmatically.

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 3 26 13 pm](https://user-images.githubusercontent.com/23220180/52751265-b6873600-2fa3-11e9-8d6a-7fc9817f8d95.png)
