### ISSUE TITLE
Result form > Result date field: Date picker doing the funky chicken again

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1174]
Observing unexpected behavior that is similar to what we fixed in the Headdesk release.

Likely depending on where I'm scrolled on the Program page when I open up the Result form, I experience some combination of the following.
1. Sometimes the date picker is docked as expected under the result date field.
2. Sometimes I click and do not see the date picker at all. (Guess based on past experience: Its coordinates are positioning it off screen somewhere.)
3. Sometimes the date picker appears somewhere else on the page other than immediately below the result date field.

The date picker does not exhibit this behavior, as far as I've seen, on Production. Request: Restore the date picker positioning so that it behaves as it does on Production.

**Comment by axoplasm** [comment]
Conditions to reproduce:

1. View the site on a viewport LARGER than the Results modal (may not be a necessary condition?)
2. Open the results modal for an indicator on the FIRST screenful (i.e. do not scroll to an indicator and then open the results modal)
3. Click in the Result Date field. You should see the datepicker as usual:
![image](https://user-images.githubusercontent.com/169060/52731552-d0f4eb80-2f72-11e9-9354-60dfd59852be.png)
4. Close the results modal and scroll down [y] pixels (not sure how far)
5. Open the results modal for another indicator
6. Click on the Result Date field. The calendar is now offset [y] pixels, *probably* where [y] is the distance you scrolled in step 4.
![image](https://user-images.githubusercontent.com/169060/52731671-24673980-2f73-11e9-92bb-f73f9cec153e.png)

**Comment by axoplasm** [comment]
FFR we previously diagnosed this bug in #399 and my original fix is in be01bf8f0

**Comment by RickieT** [comment]
**Deployment Verification**
There are still some remaining issues that will need to be fixed in what @axoplasm has described in #399, But for the purposes of this fix specificly, the date picker will remain at date picker field on click- Any resizing or zooming of the window will dislodge it a bit. 

- [x] Confirmed “Ready for Deploy” status
- [x] Media Verifying: 
![screen shot 2019-02-13 at 1 43 42 pm](https://user-images.githubusercontent.com/23220180/52746003-64d7af00-2f95-11e9-991a-a8cde4761b7c.png)
