### ISSUE TITLE
Result table: Target period column squished

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1180]
Probably due to some of the work we've done in the Evidence column, the Target Period column is now looking pretty squished -- particularly for our longer period names like "Life of Program (LOP) only and "Semi-annual period N" -- probably even longer translated.

Can we tweak the relative proportional widths to give the Target period column more breathing room, closer to what's on production?

**Comment by axoplasm** [comment]
So...this one's gonna be tricky. If we `nowrap` the whitespace in this cell, we run the risk of this:

![image](https://user-images.githubusercontent.com/169060/53055418-78cf5500-345c-11e9-91f0-5473ab7c5437.png)

…which is even worse than it looks because the table has no overflow properties so I can't scroll horizontally to the elements that are pushed off the viewport.

I can force it to greedily consume as much of the table as it wants, but that means the OTHER cells that are also trying to do the same will (probably, this varies by browser), be squashed:

![image](https://user-images.githubusercontent.com/169060/53055630-4540fa80-345d-11e9-86d5-ca212b672ac5.png)

**Comment by axoplasm** [comment]
This kind of splits the difference by setting a minimum width for that cell:

![image](https://user-images.githubusercontent.com/169060/53056185-28a5c200-345f-11e9-814b-844ecd61d28f.png)

Proceeding on the theory that LoP-only targets are going to be the most common visual case, I picked a width that catches that size:

![image](https://user-images.githubusercontent.com/169060/53056142-03b14f00-345f-11e9-9801-2c48f8449b1c.png)

**Comment by RickieT** [comment]
@axoplasm I'm looking on tola-qa, and comparing to production, and I am not sure what fix I am looking for, I don't see any differences. 
![screen shot 2019-02-20 at 10 16 56 am](https://user-images.githubusercontent.com/23220180/53114520-cc8f7c00-34f8-11e9-87ca-b871dbc75c60.png)

**Comment by RickieT** [comment]
**QA Verified:**
Based on the attchment's @axoplasm posted, I believe I am seeing a fix for this issue now. 
![screen shot 2019-02-20 at 12 41 06 pm](https://user-images.githubusercontent.com/23220180/53122999-e89d1880-350c-11e9-8a01-cfeb4e5c2a34.png)

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.
