### ISSUE TITLE
Google Drive picker is annoying

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1203]
There are some usability issues with the Google Drive file picker (used on the Result modal for evience.

- The default google drive setting is just a pile of all files the user has access to.  It would be nice if it was structured a bit better.
- The search function may not work for some users (e.g. Cameron and Jenny).
- The folder order in Team Drive is jumbled.

If the picker configuration could be updated in some way to address some of these issues, that would be great.  Of course existing functionality (e.g. Team Drive access and the ability to select folders) should be preserved.

**Comment by KennyMonster** [comment]
It's possible to filter down documents by type, and also create new tabs/panes. For instance, if you just wanted a view of only Sheets, that could be done. Another option would be separating out the files and folders into different views. This seems not overly useful though since there are filter options available to do exactly this sort of thing in the dropdown.

I haven't been able to find anything that lets you control the structure or ordering though, outside of deciding on a list vs grid view. 

It's also unclear what is broken about the search for some users.

**Comment by KennyMonster** [comment]
A pane with "My Drive" is available for testing in branch `1203_gdrive_picker_improvments`. See 560b8c1a18c83bf75632d4949be366ac3cdd1e54

**Comment by RickieT** [comment]
*QA Verified:*
The picker looks okay, though I don't have access to any team drives.

**Comment by sanjuroj** [comment]
@RickieT When you say you don't have access to team drives, do you mean through the picker or in general?

**Comment by RickieT** [comment]
@sanjuroj I don't have access to any team drives, so the option does not pop up in the picker.

**Comment by RickieT** [comment]
**Pre-Deploy Check:**
- [x] Non-regressed
- [x] Feature/fix can be found in release branch in staging environment, functioning as expected. 


If above is checked, this feature/fix is DEPLOY READY.

**Comment by sanjuroj** [comment]
I have access to a Team Drive and tried the file picker and it still works.

**Comment by sanjuroj** [comment]
Fixed in Hucklepatch

**Comment by jennyhavah** [comment]
@sanjuroj Looks like this was fixed. Ok to close?

**Comment by sanjuroj** [comment]
yup
