### ISSUE TITLE
Accordion style

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1266]
These are a bit all over the place. They currently look like:

![image](https://user-images.githubusercontent.com/169060/54154943-459b3880-4400-11e9-98d7-5ef01fd84b36.png)

Which is not far off Jenny's mockups:

![image](https://user-images.githubusercontent.com/169060/54154966-551a8180-4400-11e9-9e05-a038a98673c3.png)

But a bit of a departure from our usual style:

![image](https://user-images.githubusercontent.com/169060/54155048-8c892e00-4400-11e9-9848-45bf062f1723.png)

**Comment by RickieT** [comment]
@axoplasm I am also not seeing these changes on Dev2 as well

**Comment by RickieT** [comment]
@axoplasm which image should i be using to compare - confirm - test styling changes?

**Comment by axoplasm** [comment]
It's not really any of these. Let's run this by @jennyhavah for review.

**Comment by jennyhavah** [comment]
@axoplasm What decision do we need to make at this point? (I see that there are styling differences -- not sure what I'm being asked to review or give input on.)

**Comment by axoplasm** [comment]
You’re the final veto on this look/feel

The "usual style" shot at top is a mockup applying our usual accordion style to the new elements. When I built them I left the icons from your mockups but otherwise kept our shop style, thus:

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/169060/55365751-87b51880-549a-11e9-9f83-7c1426ea4b2d.png">

(expanded:)

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/169060/55365765-a1eef680-549a-11e9-8a05-fbaf0228075e.png">

So visually they are kind of between your and my mockups.

**Comment by jennyhavah** [comment]
Thanks for the clarification! Overall I think this approach looks good. Couple of questions:

1. For multi-select, will the check boxes go to the left of the icon? (Seems like the obvious place, just want to validate my assumption.)

2. I see that there is no expando/contracto icon for the row. This is the type of interaction that is easily discoverable, so not worried about that. The thing I'm wondering about is whether we need to also consider scenarios where there are groupings of rows _without_ expando/contracto -- and if there should be a more obvious affordance when the row is expandable. 

Here's an example of a table coming up in Satsuma where we probably do NOT want to make the gray result level rows expando/contracto:

![image](https://user-images.githubusercontent.com/33670923/55420975-11152b00-552d-11e9-8319-2ee6f5b72c6e.png)

Why not? Because (A) that's what the filters are there for (showing/hiding indicators and result levels) and because (B) We will soon be introducing disaggregations that are likely to involve expando/contracto of _indicator_ rows. Nested accordions aren't out of the question, but I question the utility in this case.

ANYWAY, what I'm getting at here is: Should we re-introduce the expando/contracto triangle to the left of the globe, to make the affordance more explicit? And if yes, does it get crazy busy with the checkbox next to the triangle next to the icon.

**Comment by RickieT** [comment]
@jennyhavah @axoplasm  Lets move this ticket through, and should the design change need be for the arrow expando, we can make a new ticket to make the change

**Comment by jennyhavah** [comment]
@RickieT I see you moved this into Ready for Deploy. One reason why Paul and I need to be the ones to make the final call on moving tickets out of development, is so that design threads like this one are not cut off without resolution. This happened a number of times in Huckleberry, where tickets fell off of our radar because they were moved into Ready for Deploy.

I'm moving this back to In development. 

@axoplasm What are your thoughts on my last comment? I don't feel strongly about timing -- if you'd like to hold off on the decision until later. We can make a new ticket as Rickie suggested.

**Comment by RickieT** [comment]
@jennyhavah If thats the case, then I expect these decisions to happen BEFORE they hit the done/ready for QA column, because when its there, thats when I'm to assume its ready for testing.

**Comment by jennyhavah** [comment]
Agreed that a ticket shouldn't be moved into done/ready for QA until all the design issues are resolved -- either as part of the ticket or by creating a new one.

Sometimes the QA process itself will reveal additional work to be done or design decisions to be made, and that's ok. Ideally, as soon as we started discussing design patterns in the comments, one of us would have moved the ticket back into "Doing" or "In Development".

Incidentally, I find it easy to overlook the status of a ticket when I arrive at it from an email tag rather than the Project Board... which is what happened in this case.

**Comment by RickieT** [comment]
**QA - PASSED**
* Expand/Contract arrows are there now, closer to our usual style.
