### ISSUE TITLE
IPTT exports: Number cells aren't formatted as numbers

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1297]
Reported by VISTA program at MCNW. I'm assuming this applies to both types of IPTT reports.

> When she goes to export an excel sheet, the numbers aren’t formatted as numbers but as text, so she has to individually/bulk convert. Can we format it correctly to reduce the effort required to convert?

**Comment by jennyhavah** [comment]
@camgnostic I don't use Excel much... What's the fastest, easiest way to test if number cells are formatted as numbers? And how extensively do we need to test? Like -- one cell per column? One target frequency or multiples? Etc.

**Comment by camgnostic** [comment]
format cells is the thing you're looking for, either right click on the cell and select "format cell" or click the cell to select it and press ⌘-1 to pop open the format cells menu.  You'll see on the first tab of the cell formatting popup a "cell type" list.  Text cells should be "General", number cells "Number", and percent sells "Percent".  Checking one or two should be fine, and you can also visually look over the sheet and any cells with a numeric value that are "General" (text) cells should have a green warning arrow in the corner (if you have a program with manual numbering you'll see all the number cells have that warning flag in them - excel thinks they should be a Number type, but we left the number cells as Text type because of RF numbers like "Output 1" which is not a number.  So if none of the result/target/baseline/etc. cells have that green arrow in their corner, then they're good

**Comment by sanjuroj** [comment]
Ironically, the only column that is formatting as text instead of a number is the "No." column (column 1). @camgnostic

**Comment by sanjuroj** [comment]
Turns out this is as expected since text values can appear in this column. 

So, PASSED, all of the values checked so far have the appropriate formatting.
