### ISSUE TITLE
SuperAdmin program permissions: Admin UI does not reflect permissions from a user standpoint

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1339]
# Issues
The following applies to the SuperUser admin role.

1. When I visit my own user account, my permissions do not reflect the fact that a SuperUser can do any damn thing. It appears as if I have:
     1.1. **Basic Admin** access to my base country (not sure why, could be a separate issue)
     1.2. **User** access to all other countries on my Accessible Countries list in Django
     1.3. No access to any other countries.
     1.4. **Low** access to all programs in any countries I have access to.

![image](https://user-images.githubusercontent.com/33670923/55440012-30c34800-555b-11e9-88b2-1253acf01118.png)

2. I can modify my program access levels between Low/Med/High, but it has no effect on what I can actually do in terms of modifying and deleting indicators and results

# Acceptance criteria

For SuperAdmins, the following things are true:

- [ ] 1. <s>My default program permissions display as High, not Low. </s>
    - [ ] 1.1. <s>I can view, but not modify, my program permission level. If I have access to a program, it's High.</s>

- [ ] 2. <s>For any country where I have a role, it displays as SuperAdmin</s>
     - [ ] 2.1. <s>I can view, but not modify my country level role. I'm either nothing or SuperAdmin.</s>

__EDIT__: most criteria are deferred to #1404

- [x] 3. BONUS: Add a banner or message to the top of the screen letting me know at all times that I’m a SuperAdmin (so don’t do anything stupid…)

## Housekeeping (where applicable)
- [ ] Unit test/s written 
- [ ] i18n strings included
- [ ] Is accessible to people using screen readers

**Comment by jennyhavah** [comment]
@hannalcamp Regarding the "God mode" banner... It occurred to me that there is already a bright red "SuperUser" badge in the user row, like so:

![image](https://user-images.githubusercontent.com/33670923/55439901-dd50fa00-555a-11e9-944f-f22aa46ad144.png)

If we make the changes described in the ticket, do you still think we need a banner? If so, what should it say, to communicate something more meaningful than the SuperAdmin badge?

**Comment by jennyhavah** [comment]
@hannalcamp Do you consider this ticket a release blocker?

**Comment by axoplasm** [comment]
I can replicate the behavior described above but there are some weird edges here that we should consider. This is because SuperAdmins can edit anything via the Django interface or Admin Lite interfaces, but not through the usual end-user UI. The most straightforward example is:

#### Given that I:

1. Am a SuperAdmin
2. do **not** have access to Country X (at User or Basic Admin level) — this is most accurately seen in the long "Country Access" section of the Django admin
3. have **no** access to any programs in Country X

#### …I can:

1. edit or delete Country X in the Admin Lite interface
2. edit or delete any program in Country X in the Admin Lite interface

#### …but I can **not**:

1. View aggregate data for Country X on its landing page (i.e. the “home page” when I select Country X from the “change country dropdown”
2. View any program landing page in Country X
3. View or edit indicators for any program in Country X — using the standard UI. I can still, with effort, change indicators via the Django admin.
4. View or edit results in Country X — using the standard UI. I can still change results via the Django admin.

Given all of this, I have a couple of proposed solutions:

1. Apply the “Super Admin” banner above so at least I know stuff should be messed up
2. Allow SuperAdmins to alter their country access status in the Admin Lite Interface (this may be possible already?)
3. *[big lift]* Give SuperAdmins full access to all countries and programs in the entire app, and disregard their entries in the Country Access table.

**Comment by axoplasm** [comment]
Sorry, I just realized I *can* edit indicators and results for a program I have no access to, if I have the URL bookmarked or can reverse-engineer the URL. The only thing I can’t do as a SuperAdmin without User access privileges is view the aggregate country data or see programs on the country landing page

**Comment by hannalcamp** [comment]
@axoplasm And this is due to the back-end fix we had Parthenon do in order to prevent partner users who don't have whole-country access from seeing all programs on the country landing page, correct?

Ultimately I think we will want to do the big lift option 2 in order to make the Super Admin experience cleaner and more straightforward. However, I don't want this to be a release blocker, as the Super Admin experience is one only a few of us will be having and can be easily fixed by us just giving ourselves User access to all countries in the Admin Lite UI. In order to demonstrate regular user experience to others, we really need to be using demo accounts. So for now I say let's go with Option 1. @jennyhavah Any objection?

**Comment by jennyhavah** [comment]
@hannalcamp No objections to deferring The Big Fix. 

Regarding a super admin banner, @axoplasm, I think it's pretty clear that I'm a SuperAdmin with this thingie.

![image](https://user-images.githubusercontent.com/33670923/56150181-25145000-5f63-11e9-91be-fd34ae64a6af.png)

I'm also not sure how making it more obvious that I'm a SuperUser adds any clarity as to why stuff appears confusing or broken. (I included it in the original ticket before I realized there already is that bright red badge.)

**Comment by axoplasm** [comment]
I can also add something like this:

![image](https://user-images.githubusercontent.com/169060/56151234-ac62c300-5f65-11e9-8f83-3e80faf6fada.png)

**Comment by jennyhavah** [comment]
@axoplasm That means that, as a SuperUser, it will be permanently red... Which I find a bit intense. Even though it's MC red, the combination of reds reads like "alarm" to me.

Also, I'm just not understanding why it's so important to remind ourselves that we're SuperUsers. Outside of this very narrow testing period of time where we're testing roles and permissions, we always login as SuperUsers.

**Comment by axoplasm** [comment]
I don't feel strongly about that red background. I also recognize that our Super Admins often give demos from their own accounts and the UI shouldn’t look too crazy for that reason.

Because of the way permissions are kind of layered on top of each other, this particular interface will always lie to the user somehow. IMO it doesn’t so much look “broken,” rather in some cases the lies are more obvious.

**Comment by axoplasm** [comment]
The only changes I made here are badges in the page head. I’ve created a new ticket (#1404) for faking full access for Super Admins throughout the app.

**Comment by jennyhavah** [comment]
@axoplasm By "badges in the page head" do you mean these?

![image](https://user-images.githubusercontent.com/33670923/56154498-817c6d00-5f6d-11e9-9dff-c9280e16ee73.png)

**Comment by axoplasm** [comment]
Yes

**Comment by RickieT** [comment]
@axoplasm 
So this ticket is just purely adding the badge at the top of the page, and the "faking" you mentioned is being resolved in another ticket?

If thats the case, this passes QA. 
![Screen Shot 2019-04-15 at 11 28 16 AM](https://user-images.githubusercontent.com/23220180/56156258-b68abe80-5f71-11e9-974f-35150be67b21.png)
