### ISSUE TITLE
Global: Disabled/enabled checkboxes are practically indistinguishable

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1377]
Affects: Global. While the example given is from the Admin console, this issue applies to any checkbox list that includes both active and inactive items. 

Note: The particular screen used as an example has numerous UX challenges that are tackled in other tickets such as #1500 and #1532. This ticket only addresses a narrow visual design issue with the checkbox elements themselves.

# Issue

Reported by Cameron: In user admin program selection disabled/enabled checkboxes are practically indistinguishable. Here I am a user who has admin access in the country for the top half of this screenshot, and don't have admin access for the bottom half.  So the top half of this screenshot the buttons are checkable, the bottom half they are not.  It is not visually clear without clicking on them which ones will work.

![Screen Shot 2019-04-30 at 12 09 45 PM](https://user-images.githubusercontent.com/7941355/56986973-11f7a780-6b41-11e9-9ac9-edb69d05dd6a.png)

# Acceptance criteria

- [x] It is easy-peasy-lemon-squeezy to tell active and inactive checkbox items apart.

Visual pattern TBD by Paul. Suggestion from Jenny: When a checkbox is inactive, the text next to the checkbox is grayed out as well. That way, the user doesn't need to notice subtle shade differences in the tiny gray outlines of the checkboxes themselves.

**Comment by jennyhavah** [comment]
@camgnostic, can you please clarify which view you mean, exactly, and include a screenshot?

**Comment by camgnostic** [comment]
Here I am a user who has admin access in the country for the top half of this screenshot, and don't have admin access for the bottom half.  So the top half of this screenshot the buttons are checkable, the bottom half they are not.  It is not visually clear without clicking on them which ones will work.
![Screen Shot 2019-04-30 at 12 09 45 PM](https://user-images.githubusercontent.com/7941355/56986973-11f7a780-6b41-11e9-9ac9-edb69d05dd6a.png)

**Comment by jennyhavah** [comment]
Thanks, @camgnostic Updated the ticket.

**Comment by axoplasm** [comment]
These are browser- and OS-standard widgets. Styling them directly is usually considered a Bad Idea. For a couple reasons:

1. Users are theoretically conditioned to see these a particular way _across all websites_, fiddling with them defies their expectations
2. Some browsers use the OS UI kit to draw them, so they should be consistent throughout the UI (for the same reason as 1)
3. bc of Reason 2: they are not amenable to direct restyling, __AND__
4. Their default styling will change when the browser or OS changes

Disregarding all that, I fiddled with the opacity a little:

![image](https://user-images.githubusercontent.com/169060/57100206-2ec3e480-6cd3-11e9-802e-4c442e3629aa.png)

The usual practice is to use JS or css pseudoelements to draw in our own elements that we have more power over. Bootstrap has a couple of helpful things there:

Custom checkboxes & radios: https://getbootstrap.com/docs/4.3/components/forms/#checkboxes-and-radios-1

Switches instead of checkboxes: https://getbootstrap.com/docs/4.3/components/forms/#switches

**Comment by jennyhavah** [comment]
I think the change in opacity is just fine for now, and we can continue improving things in #1543. 

From my perspective, this ticket is done.

**Comment by jennyhavah** [comment]
PASSED. The active checkboxes are much easier to differentiate from the inactive ones.

![image](https://user-images.githubusercontent.com/33670923/57164615-86cd1a80-6da9-11e9-94a6-f5de60d13994.png)
