### ISSUE TITLE
Program page: Missing Program to date info

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1392]
I’m not sure how big this bug is. There's an errant % sign for "Program to Date" subtotals on the program page.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/169060/56061847-7b914c80-5d1f-11e9-9991-d3244597fcf8.png">

compare with similar indicator on Production:

<img width="881" alt="image" src="https://user-images.githubusercontent.com/169060/56061876-8d72ef80-5d1f-11e9-9a85-ff2012621d84.png">

There are potentially two things wrong here:

1. The errant % sign, which if not calculated should simply be an em-dash (—)
2. Should there be a program-to-date subtotal there?

**Comment by jennyhavah** [comment]
@camgnostic Can you please take a look, let us know what type of problem it is, and whether you've already solved it on the Satsuma branch?

I don't consider this a release blocker for Papaya _unless_ there's some sort of calculation issue we should resolve right away.

**Comment by jennyhavah** [comment]
I looked into this a bit more. It's not just an errant % sign -- a whole row of data is missing, and there's a discrepancy between Production and Dev2. For that reason, I'm moving this back to Papaya.

Here's an example from Jordan's WIT program where program to date info is NOT visible on Dev2 but IS visible on Staging.

![image](https://user-images.githubusercontent.com/33670923/56167216-6f5df700-5f8c-11e9-97e7-45c2388ba707.png)

And here is a different Annual indicator _from the same program_. 

![image](https://user-images.githubusercontent.com/33670923/56167374-dda2b980-5f8c-11e9-8bf3-5f2d509a3763.png)

I'm also wondering why the first indicator has dashes for Targets and Actuals while the second one doesn't, since they share a program period and target frequency.  (That may be a different, and non-Papaya specific issue, which we can move to a different ticket if need be.

**Comment by axoplasm** [comment]
My notes for the night, will tackle this tomorrow. I bet @camgnostic can go right to this fix.

the component in `indicator_list.js` that renders the results table is `DangerouslySet`ing`InnerHtml` with `resultsStr`. 

This loads the `results_table.html` template, which renders this using the `target_percent_met` (`target-percent-met.html`) template tag. So far so good.

__here’s the breakdown:__ that template tag takes as its argument a floating point value, in this case `indicator.lop_percent_met_progress`. It appears this value (and possibly `indicator.lop_actual_progress` and `lop_target_progress`) are not being annotated correctly i.e. via `indicator_lop_percent_met_progress_annotation` in `indicators/queries/utils.py`

I’m not sure if this is a failure somehow of the react component not running these queries (which I don’t understand) in `DangerousSetInnerHtml`, or if something upstream from `utils.py` is not working.

**Comment by jennyhavah** [comment]
@camgnostic Assigning to you not to pile more tickets on, but just to make sure you have a chance to look before we act, as Paul said this is related to something you've been working on. He's happy to keep working on it -- just let us know.

**Comment by RickieT** [comment]
**QA - PASSED**
* Checked multiple programs, all showing program to date now (Where applicable) :
![image](https://user-images.githubusercontent.com/23220180/56307963-f5984b80-60fa-11e9-9337-2ef1325ca5fd.png)
