### ISSUE TITLE
Deleted indicator remains on page if user navigates away, returns

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1423]
I think as a side affect of #1370 this issue may have spawned, but I could be wrong. Onto the issue:, see media: 
1. I Deleted an indicator, was given proper warning confirm, and the indicator disappeared from the program page. 
2. I then navigated to the Recent progress report page, and then hit the back button to return. 
2. The indicator I deleted remained on the page when I returned after viewing the recent progress report IPTT. Clicking it gave me a 400 error. Reloading the page, the indicator then disappeared again, permanently.

![re-appearing_magic](https://user-images.githubusercontent.com/23220180/56241228-31bfa380-604a-11e9-81de-6bfa70e615d7.gif)

**Comment by jennyhavah** [comment]
@Rickie Thornley Looking at your screen capture, is it possible you’re not seeing @cameron’s most recent code? I remember him talking about these “ghost indicators.”

Cameron, is this already covered in some of the work you did in the last couple of days that isn't yet deployed to Dev2?

**Comment by camgnostic** [comment]
Investigated this today.  It... is not an easy fix.  Will require overhauling how the program page calls for initial data.  (Before another dev comes in and repeats my trials, things I tried to get the program page to reload stale data:
 - cache-control headers
 - all cache-related meta headers
 - window.onpopstate, window.onpageunload, window.onpageshow listeners looking for various settings (in window.history or window.name)
 - getting popstate state from the router5 meta source tag (it's always undefined)

Options: 
1- (medium effort, like 2-3 hours and slight regression risk) we change the page so it does not load initial data with the page, but calls for it from an API, which would call for and receive fresh data on the back button
2- (low effort, minimal regression risk) force a page reload every time a user deletes an indicator.  Pros: easy.  Cons: other changed data will still be wrong when a user navigates away and then returns.  
3- we leave it the way it is.  If you go to any website and fill out some fields, then navigate away and hit "Back", you get stale data.  This is why credit card processing pages ask you not to use the back button (or just disable it).  There's some unpredictable behavior involved in the back button because every browser does it differently.

@jennyhavah how do you want to proceed?

**Comment by jennyhavah** [comment]
Update: Cameron and I just chatted on Slack. Both of us are inclined towards 3, because 2 doesn't fully solve the problem and 1 has regression risks.

One thing that would help in a small way would be to have a more informative error message. Instead of "404 Not found", we could say something like "Indicator was recently deleted." We apparently only "soft delete" and so this could potentially be an easy fix.

@camgnostic is looking into how easy this is.

**Comment by jennyhavah** [comment]
@KennyMonster Actually, if you have time to grab this last bit with the error message and let us know if it's easy or not, it would be much appreciated! Cameron's going to be working on event targets for a while longer...

**Comment by KennyMonster** [comment]
@jennyhavah I think I found a reliable way for the page to detect if it is being loaded from a disk cache, and to reload it self to ensure the data is up-to-date. This fixes the problem testing locally. The downside of course is we are bypassing the cache which exists to help with performance, especially for those on slowish internet connections. So it's a performance vs correctness tradeoff.

I tried to figure out a way to record if the data is stale and if the cache is be invalidated, but this is also getting messy.

If you are ok with effectively disabling the page cache for this page only, I can push the change.

**Comment by jennyhavah** [comment]
@KennyMonster would the page cache be disabled / page reloaded ONLY if you're using the back button, or would the reloading happen at other times as well? 

More broadly, I want to make sure we're not interfering with the React-iveness of the page as a whole, just to address this back button issue.

**Comment by KennyMonster** [comment]
The reactiveness shouldn't be affected. The check happens on page load: if the page was loaded from the disk cache instead of the network, it force reloads from the network. Otherwise it should work as-is.

**Comment by RickieT** [comment]
**QA - PASSED**
* This issue no longer persists as written, mostly. The deleted Indicator will disappear in just a quick second once returning to the page, so I think this gets a passing grade. 
![passed](https://user-images.githubusercontent.com/23220180/56375483-82eea500-61ba-11e9-8d9c-6f6a4941fe71.gif)
