### ISSUE TITLE
Programs drop-down in Sites should only show programs the user has access to 

### ISSUE THREAD

**Issue by hannalcamp** [mercycorps/TolaActivity#1478]
**Affects:** Sites landing page for all users.

# Issue
On the Sites homepage, the drop-down list titled "Programs" is currently filtered according to the country the user has access to. However, if the user has access to only a few programs in that country, they can still see a list of all programs, instead of only the ones they have access to. The options in this menu should be restricted by program access, rather than by country access.

# Acceptance criteria

- [x] 1. When a user with access to one program (any User Role) goes to the Sites landing page, they only see that one program name in the drop-down.

- [x] 2. When a user with access to multiple programs (any User Role) goes to the Sites landing page, they only see those program names in the drop-down.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by axoplasm** [comment]
This is not difficult but I need a sense of, is this a release blocker? It means redefining a filter we use commonly on lots of older workflow views, e.g. Documents

**Comment by hannalcamp** [comment]
Hm, @jennyhavah this is in some ways a workaround to the problem of us showing Sites that program-specific users don't have reason to see - but it would result in a blank map for some people. I'm inclined to do it even though it's not the best solution to the problem?

**Comment by jennyhavah** [comment]
@hannalcamp I agree that this is preferable to exposing the full list of programs to users who shouldn't be seeing it.

@axoplasm I'd only do this if it's easy, but since it'll be pretty common for external users to have access to only one program, and for that program to have no sites, perhaps we add a message in the middle of the gray box: [Program name] has no program sites.

**Comment by axoplasm** [comment]
Setting aside ease of implementation, what is our desired behavior for the Sites list generally? Should I be able to see all sites? Only those in my program(s)? Countries in which I have program(s)? What if I need to add a site from another program?

**Comment by jennyhavah** [comment]
@axoplasm All of these are good questions that don't have obvious answers, and we have not yet done the discovery work to be able to answer them with confidence. We ultimately need to rethink Sites altogether, and engage the PaQ team in figuring out what this feature set ought to be.

For Papaya, I'm mainly concerned about the security implications of being able to see a list of Programs you don't have access to.

**Comment by axoplasm** [comment]
Right now, map and dropdown aside, any user can see all sites in the list itself. I remember having some discussion on this. I will do some archaeology to figure out why. Maybe it fell through the cracks. 

It's relatively simple to filter this list, but I need to sketch out some business rules first.

**Comment by axoplasm** [comment]
I have narrowly addressed _just the Programs dropdown_ in 10d74adf:

![image](https://user-images.githubusercontent.com/169060/56826492-400f7b80-6811-11e9-9a59-81e53befca3e.png)

This still leaves a lot of apparent mystery (to me) around what Sites get rendered, and why. This is due to the old way that we used to route requests, for example when you use the Program “filter” what you’re actually doing is changing the URL. I will make a ticket for addressing how the Sites page is routed and filtered, suggest we defer that ticket tho.

**Comment by RickieT** [comment]
### QA Passed:
* Confirmed, only programs user has access to is showing in the droplist now as shown above:
