### ISSUE TITLE
TolaTestThree account is getting an error attempting to login through okta

### ISSUE THREAD

**Issue by RickieT** [mercycorps/TolaActivity#1522]
Using the account tolatestthree@mercycorps.org, user is presented with a error page message, and does not log the user in:
![Screen Shot 2019-04-29 at 12 57 32 PM](https://user-images.githubusercontent.com/23220180/56923709-1740ed80-6a80-11e9-9536-cd1b42966d51.png)

**Comment by sanjuroj** [comment]
When users log in through Okta, there are several other bits of information that we get from Okta:  first name, last name, and country assignment.  The Okta login code does not currently handle errors in retrieving/processing this information particularly well.  This particular issue is probably related to the very long last name that was given to the tolatestthree account.

Unfortunately, for messaging, since it's related to login, it's a bad idea to be too user friendly.  A generic message similar to the one we're using for Google is probably best, something like "This Okta account is not associated with a TolaActivity user account."  Below that an indication of where they can get help.

Here's what I'd like to propose we do to address the potential issues related to first and last names and country assignments.

Field from Okta | Value in DB exists | Value in DB doesn't exist | Rationale 
--- | --- | --- | --- 
First and last name | Continue, but log | Log and deny access |  If value of at least one of them is already in DB then everything will appear normal to user, and a name will appear in the logs.  If a value not in the DB, the User field in the logs would be blank, which I'm assuming we don't want.  
Country | Log and deny access | Log and deny access | If the country assignment isn't provided by Okta or is not recognized, we can't be sure that we are giving the user access to the correct Country.

**Comment by jennyhavah** [comment]
@sanjuroj This all sounds fine to me.
