### ISSUE TITLE
User's country assignment doesn't show up in admin

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#1551]
When an MC user has a home country assigned, that country doesn't appear with any permission in the user's admin listing.

**Comment by axoplasm** [comment]
Checked this out on my local. I want to be clear on the behavior I experience, hopefully this is the expected behavior.

Aaron Aaronson has no country access in the Django admin:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/169060/57339860-2fe87d80-70e8-11e9-8259-73403562dd57.png">

…and no access to any country (example: Bangladesh) in admin lite:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/169060/57339845-16473600-70e8-11e9-827f-81d269fed97f.png">

I use the Django Admin to give Aaron access to Bangladesh:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/169060/57339816-f31c8680-70e7-11e9-9504-3c9dfb63a35b.png">

__I need to reload the user admin (http://127.0.0.1:8000/tola_management/user/#)__

Then I see he has "User" access to Bangladesh:

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/169060/57339917-750caf80-70e8-11e9-8e76-44882885aa25.png">

**Comment by sanjuroj** [comment]
On the refreshing issue, I don't think there is any way for React to be triggered by a change that's coming from the Django admin.  That's a bit like reaching into the database directly and updating the data, which React can't respond to either.  Not unless we start doing pushes to the page. 

I _think_ the inability to unset the home country is expected behavior.  Home country assignment is supposed to come from Okta, so it should not be modifiable by country admins. And if they could change it, the next time the user logs in it would get set back to the home country, potentially causing some confusion.

**Comment by axoplasm** [comment]
we *might* want to change the success message to reflect this. “You cannot revoke a User’s access to their home country as defined in Okta” or somesuch. Maybe. I have a feeling this is a really outside edge.

**Comment by sanjuroj** [comment]
Ideally, it would not be possible to even change the person to "Individual programs only".  It might also be nice to note on the form that this is the user's home country and authorization to this country can't be downgraded.  All that said, I think I would prefer to deploy the fix as-is and work out the niceties later.  @hannalcamp?

**Comment by hannalcamp** [comment]
@sanjuroj Agreed, I think the way we explain full country access vs individual programs access might have to evolve a bit as we discover what works. Deploying a fix and tweaking it as needed seems right to me.

**Comment by hannalcamp** [comment]
As a Super Admin on QA, I set a user's home country to Central African Republic (no accessible countries), and saved. That user then was able to see CAR on their home page and all its programs. This program access also reflects in the Admin Lite UI. However, the programs list for the user still shows 0.

![Screen Shot 2019-05-09 at 10 14 27 AM](https://user-images.githubusercontent.com/38020496/57469283-89b18a80-7243-11e9-93f9-8e2cfbf472d9.png)

**Comment by hannalcamp** [comment]
@sanjuroj I wouldn't consider this a release blocker, but if it's fixable within this ticket we should probably do so?

**Comment by sanjuroj** [comment]
Yeah, I'm looking at this right now.  The issue sort of extends out to anywhere we derive a list of programs from someone's associated countries.  There are several places where this list is generated and each one should probably be changed.

**Comment by sanjuroj** [comment]
@hannalcamp I opened another ticket (#1559) for the program counts.  I really don't want to hold up the multi-select fix since it is potentially altering data.
