### ISSUE TITLE
RF Builder levels (empty)

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1570]
Refers to the level builder in its empty state:
![image](https://user-images.githubusercontent.com/169060/57649267-a23fde80-757c-11e9-9270-0e87a3d1a5d1.png)

**Comment by jennyhavah** [comment]
@axoplasm The empty state needs a bit more breathing room between the title row and the body section implemented in this ticket. Here's what I see on Chrome:

![image](https://user-images.githubusercontent.com/33670923/58840333-13bdfa80-861a-11e9-8046-aac8ccba23e5.png)

Below is the mockup for reference -- I have the body chunk more or less vertically centered, but even just a healthier amount of padding at the top would be fine -- whatever works best from a responsive standpoint.
![image](https://user-images.githubusercontent.com/33670923/58840308-fe48d080-8619-11e9-9b85-7fb411d1a2cb.png)

**Comment by jennyhavah** [comment]
@axoplasm A couple more suggestions. Here's what I'm seeing, using an example of a long program name, which is typical.

![image](https://user-images.githubusercontent.com/33670923/58908226-d793a400-86c4-11e9-964f-960474ce6859.png)

1. The program name has a much stronger presence than the part of the title specific to this page -- "Results framework". My intention was that both portions of the title string would have roughly the same weight. If either portion has to be more dominant, it ought to be "Results framework".

2. It looks crowded above and below the title row -- can we add a bit more vertical padding?

3. I wonder if the Logframe button would look better if it was top aligned rather than center aligned with the title?

**Comment by axoplasm** [comment]
I can tweak the font size in the title a little but I'm not crazy about messing with the top margin or alignment for the logframe button. These styles rely on shared components and tweaking them for this page would introduce visual regressions

![image](https://user-images.githubusercontent.com/169060/58909862-fc8a1600-86c8-11e9-81fd-cb5e099ba0a1.png)

**Comment by jennyhavah** [comment]
I think it's okay for now -- will move to Passed column. 

At some point, maybe we can do a styling pass with a focus on titles -- font size, bolding, hierarchy, etc. It's pretty varied right now. 

For example, here's the change log -- title first, then program, program is not linked.

![image](https://user-images.githubusercontent.com/33670923/58920683-2b63b480-86e8-11e9-8456-2b2b45af9479.png)
