### ISSUE TITLE
RF Builder: Indicator widget (was: Level(s) (Expanded/with form))

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#1572]
![image](https://user-images.githubusercontent.com/169060/57661879-9dd9ec80-75a1-11e9-8ea0-55c743e42d0b.png)

**Comment by jennyhavah** [comment]
@axoplasm a few things:

1. I'm not seeing the most recent mega button treatment you and I decided on last week. Can you please merge that in?

2. There needs to be more vertical space between the RF text box and the Assumptions text box -- a bit crowded. (See screenshot below.)

3. The form label for Assumptions appears to be the same text treatment as body text. I tried to mimic your label styling in my mockup -- I recall it being a smaller font, and maybe a dark gray instead of black?

What I'm seeing:

![image](https://user-images.githubusercontent.com/33670923/58840740-ac08af00-861b-11e9-8a5a-23ffd45da4bc.png)

**Comment by axoplasm** [comment]
this branch isn't merged yet. I'm working on it now

**Comment by jennyhavah** [comment]
Looking good!
