### ISSUE TITLE
IPTT Indicators filter: Indicators unassigned to RF levels sometimes don't display when checked

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1662]
This appears to be specific to indicators unassigned to RF levels, but not 100% sure.

# To reproduce

1. Run a Recent Progress IPTT report for QA Jenny
2. In the Indicators filter, scroll down to the list of unassigned indicators
3. Try clicking the first three in the list. Note that they don't return any indicators.
4. Try clicking some others in that list and note that they DO appear.

🤔

**Comment by camgnostic** [comment]
So it turns out this isn't a bug with the IPTT.  This is a bug in indicator saving that I'm _fairly certain_ has been fixed, but I will add another DB-level check to ensure this can't happen again.  What happened is: somehow some of your indicators have been assigned to levels in Hanna's program.  So that explains their inconsistent appearance - when we grab all the indicators for the program it appears, but if I show all the indicators for each level it's only looking at the levels in your program, so it has nowhere to display it.  This should obviously never happen.  I'm adding a DB constraint and double-checking form logic to make sure there's no way to assign an indicator to a level with a mismatched program_id, but that's how this bug was started - and it was possible until I pushed a fix recently to see levels outside of your own program in the indicator form, so I'm pretty sure I know how we got to this state.

**Comment by camgnostic** [comment]
To check if other "ghost" indicators are part of this same bug, open the indicator edit modal.  The 'results level' form field will be empty. To fix, for individual indicators, simply open the edit modal for "ghost" indicators, give them a results level, and save them.

**Comment by jennyhavah** [comment]
Sounds good! Since it's no longer possible to reassign indicators to RFs from other programs, I can't reproduce the issue.
