### ISSUE TITLE
Pinning is working inconsistently

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1677]
Some things that have happened the last few times I tried to pin a Target vs Actuals IPTT:

Second pin appeared to overwrite / replace first pin.

404 error when attempting to delete a pin -- maybe connected to the above issue, the system couldn't find the thing to delete? Pin does not go away.

Run TvA on QA Jenny -- Annual

Go to program page and click pinned link 

Switch to a different program -- I used "Second program to test RF builder empty state"

Now go back to program page.

Note that first pin is altered.

That, time I was able to delete the first pin, but another time I wasn't.

**Comment by KennyMonster** [comment]
I've tested "QA Program - Jenny" locally and on QA, with every combo of filter options, and I was unable to reproduce the issue. 

Per on chat, perhaps related to recently fixed bad LoP only indicators?

**Comment by jennyhavah** [comment]
@KennyMonster @camgnostic I'm letting you both know this because this could potentially be related to issues Cameron is working on in #1629. It may also be a weird edge case, as this is a ONE MONTH program.

Check out the pins on this program page: https://tola-activity-qa.mercycorps.org/program/636/#/

In each of these cases, I set it to "Most recent 1 [period type]". But when I click on the pin, it defaults to Show All periods.

**Comment by KennyMonster** [comment]
@camgnostic I looked into this and there seems to be a redirect happening here. Well not a redirect really since it's an ajax call that changes the route and the data being displayed after the initial request, but it sorta looks and acts like a redirect.

Initial request URL:

https://tola-activity-qa.mercycorps.org/indicators/iptt_report/636/timeperiods/?frequency=7&start=0&end=0&groupby=1

The page returns a 200 and the page loads. The JS then does an ajax request to:

https://tola-activity-qa.mercycorps.org/indicators/iptt_report_data/?programId=636&frequency=7&reportType=2

After this ajax request is processed, the browser URL is set to:

https://tola-activity-qa.mercycorps.org/indicators/iptt_report/636/timeperiods/?frequency=7&start=0&end=24&groupby=1

All this is to say that what was a "Most recent 1 month" report gets turned back into a "Show all" report.

**Comment by jennyhavah** [comment]
Thanks for the update @KennyMonster. Once the fix is deployed, just drag it over to the Testing column.

**Comment by jennyhavah** [comment]
@camgnostic Can you please summarize what the issue case was, exactly, and how best to test your fix?

**Comment by camgnostic** [comment]
Issue: when setting "most recent" while also updating the old-format url parameters, the change to "most recent" periods was lost while the url parameters were being reformatted.  So while the system correctly interpreted "most recent: 1" from the input parameters, it lost that change.  To test, follow the default IPTT most recent progress link from a program with either only 1 elapsed month, or 2 elapsed months, and ensure that it displays the correct most recent periods value when the page loads.

**Comment by jennyhavah** [comment]
@camgnostic  Hmm, I'm seeing the fix when I pin Most Recent 1 Thing, but still defaulting to Show All when I pin Most Recent 2 Things...  for both styles of IPTT.

At the same time, the default Recent Progress pin that you automatically get for all programs works as expected.

You can see all the permutations here:

https://tola-activity-qa.mercycorps.org/program/638/#/

![image](https://user-images.githubusercontent.com/33670923/59806281-b0ce9380-92a8-11e9-96b7-546b88e921d8.png)

**Comment by jennyhavah** [comment]
Retested the four types of reports described in my last comment -- all look good.
