### ISSUE TITLE
IPTT 500 error and program page failure: SAFAL II program

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1817]
# Program page error

I'm getting an "ValueError at /program/457/" error page when I try to load the program page, for that same program - https://tola-activity-qa.mercycorps.org/program/457/

Here's the time stamp: Mon, 15 Jul 2019 11:31:09 -0700

# IPTT error 

I'm getting a 500 Internal server error when I try to load the Recent progress report for SAFAL II: Sustainable Access to Finance and Livelihoods: 

https://tola-activity-qa.mercycorps.org/indicators/iptt_report/457/timeperiods/?frequency=6&start=0&end=2

**Comment by sanjuroj** [comment]
Initial assessment:  This seems to be restricted to numbers with 1 number followed by one letter (e.g. 2a).  Changing the output_field and/or the casting in IndicatorSortingQSMixin fixes the error, but may also mess up the sorting that is output.  Because the conditions that lead to this error are so specific, it affects very few programs.  Was able to confirm that program id 340 has the same issue, because of numbers like 2a associated with some indicators.

**Comment by jennyhavah** [comment]
I am able to view the SAFAL program page now.
