### ISSUE TITLE
Indicator dialogue > Targets tab: Add evidence to a baseline

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#19]
**THIS STORY IS ON HOLD** (See first comment)

<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Tuesday Dec 12, 2017 at 05:55 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/9_

----

**Prioritization note:** This is a lower priority feature. The need was inferred from conversations regarding best practices in associating evidence with data. 

**User story:** When I identify a baseline value for my indicator, I want to attach evidence (such as a baseline survey) so that future reviewers know how we arrived at that number.

**Background:** We encourage teams to associate evidence with all of their indicator data. But currently it's not possible to associate evidence with a baseline value. This solution allows data collection records to be associated with a baseline.

**ACCEPTANCE CRITERIA**
1. Next to the Baseline text box is a button labeled _Add evidence_. 
2. The link pops up a modified version of the _Collected Data_ form. The differences are as follows:
2.1. The name of the form is _Baseline Evidence_ instead of _Collected Data_.
2.2. The label _Date collected_ is renamed _Date submitted_. We're making this change to be consistent with Issue #10 .
2.3. There is no _Periodic Targets_ dropdown, because a baseline does not have a target value associated with it.
2.4. The _Achieved_ field is replaced with a non-editable field called _Baseline_ that mirrors the baseline value in the _Targets_ tab. (The baseline is your starting point, so there is no "achievement" to capture in this record. The purpose of the form is simply to associate evidence with your baseline value. We include that value for helpful reference.)
3. After saving the _Baseline Data_ form, the following occurs:
3.1. The system gives you a success message, "Success: Your baseline data was saved. You can find it alongside other data records for this indicator."
3.2. The baseline data record appears on the Indicators page, treated exactly like all of the others.
3.3. Opening a baseline data record from the Indicators page takes you back to the modified _Baseline Data_ form, not the ordinary _Collected Data_ form.
4. It is possible to associate multiple data records with your baseline, but you can only do this from the _Targets_ tab. You cannot associate data with a baseline by clicking _New Data_ on the Indicators page.

**UI DETAILS**
_Add evidence_ button background color is #0083c0 and border color is #0072a7 -- same styling as the old Form Help/Guidance button.

![baselineevidence](https://user-images.githubusercontent.com/33670923/33968673-0d655b86-e01e-11e7-958b-49dd4f26cb13.png)

**Comment by jennyhavah** [comment]
Mahmood and I just had an in-depth discussion of this feature, and realized that the scope is larger than we initially thought. There are a number of open questions and issues we need to explore in order to effectively implement the feature. We may need to break this story down into several tickets. 

**Open questions/issues**
1. How do we handle disaggregation?
1.1. Of the baseline -- Baseline is 50 men and 50 women
1.2. Of the baseline data record -- survey of village A has 30 men and 20 women, survey of village B has 20 men and 30 women.
1.3. Of the LoP target: We also need to capture the disaggregation of our LoP target, to compare with baseline.
1.4. From a UI standpoint, we need to differentiate the data entry of the _baseline_ disaggregation from the data entry of the _evidence_ disaggregation. (My original concept doesn't make a distinction.)
2. How do we display baseline evidence?
2.1. Can't be integrated targets/actuals data record table -- makes it way too complex to digest.
2.2. Do we want to show how individual data records contribute to baseline? This may introduce all of the same complexities related to type of indicator -- number, percent, index, etc.
2.3. What should the interaction be for accessing baseline evidence?
2.3.1. Add baseline number to indicator row, as a button or link. Clicking on it expands the row. Instead of showing the target/actuals data table, we show a baseline table with links to evidence.
2.3.2. Add baseline number to indicator row, as a button or link. Clicking on it gives you a popover with a baseline table with links to evidence
2.4. Whichever approach we take, we need to afford the following actions:
2.4.1. Access the actual evidence -- the Google sheet, Word doc, TolaTable, etc.
2.4.2. Access the _record_ for that evidence, to view edit the value, the disaggregation details, etc.
2.4.3. Add a new piece of evidence.

**Comment by jennyhavah** [comment]
The product has evolved so much since this ticket, that it would be easier to start over with a new ticket than to update this one.
