### ISSUE TITLE
Prevent duplicate Country level disaggregation types

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#1913]
# Issue

Right now, it is possible to save multiple disaggregations with the same name, within the same country.

![image](https://user-images.githubusercontent.com/33670923/64271835-f20f3080-cef2-11e9-8bd2-ca5810e4b4cf.png)

We need to prevent this, going forward. (Any existing duplicates can be managed via archiving and renaming.)

# Acceptance criteria

- [x] 1. When I create a new Country disaggregation, the system automatically checks to ensure that the name I've typed in is not already in use _in the same country._ 

- [x] 2. If the name is already in use, I see a warning message under the Disaggregation field: There is already a disaggregation type called "[whatever they typed]" in [Country]. Please choose a unique name.

- [x] 3. QA check: I am NOT prevented from using a disaggregation name because it's already used in a _different_ country.

## Housekeeping
* [ ]  Unit test/s written wherever applicable
* [ ]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by sanjuroj** [comment]
@jennyhavah For this ticket and #2153, how strict do we want to be in preventing duplicates?  Since we can do a really strict version until we've cleaned up the existing dupes, here are a couple of options:

1. For existing duplicated types/labels, prevent existing labels/types from saving any changes unless the name is also changed.  For instance, you wouldn't be able to change the sort order of a label if you didn't also change the duplicated name to something unique.
2. For existing duplicated types/labels, allow changes to attributes but maintain the duplicated name.  So I would be able to change a sort order of a label even if it was a duplicate.

**Comment by sanjuroj** [comment]
@jennyhavah Another question related to saving.  Should duplicated types or types with duplicated labels be archivable or unarchivable?

**Comment by jennyhavah** [comment]
Message appears when expected:

![image](https://user-images.githubusercontent.com/33670923/74992308-8c5d2500-53fc-11ea-8dd3-6f6a894b5ad1.png)

But the wording is different than I had requested. I requested: There is already a disaggregation type called "[whatever they typed]" in [Country]. Please choose a unique name.

**Comment by jennyhavah** [comment]
Unexpected behavior similar to what I discovered in ticket 1913. What I did:

1. Created a duplicate disaggregation in Tolaland. Was blocked as expected.

2. Went to a _different country_ -- Bahamas -- and clicked "Add disaggregation".

Here's what I saw, before typing anything:

![image](https://user-images.githubusercontent.com/33670923/74992525-30df6700-53fd-11ea-8c03-21cfa45d6b16.png)

**Comment by jennyhavah** [comment]
Passed -- all issues fixed.
