### ISSUE TITLE
Indicator modal: clean up disaggregation lists

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#2096]
There are two expand arrows showing up next to the disaggregation categories.  

<img width="535" alt="Screen Shot 2020-01-03 at 6 03 57 PM" src="https://user-images.githubusercontent.com/6685499/71758385-e35e6900-2e53-11ea-9f45-c39a298a8529.png">

![image](https://user-images.githubusercontent.com/33670923/72390647-13253080-36e0-11ea-9c3c-aea33afa17eb.png)

**Comment by axoplasm** [comment]
this is weird enough that it will either be really easy or really hard

**Comment by axoplasm** [comment]
> this is weird enough that it will either be really easy or really hard

A little bit of both, actually! It was easy to fix with jQuery, which is how we did the accordions elsewhere in the indicator modal.

But it will be hard(er) to do this in React, which is how we do accordions almost everywhere else.

**Comment by axoplasm** [comment]
See previous note about LOE. Easy w/jQuery but *should* be React, which will be harder

**Comment by jennyhavah** [comment]
@axoplasm Would it be easy or hard to have the carets and disaggregation type headers either:

- line up with the checkboxes - OR - 
- be slightly _outdented_ rather than _indented_?

![image](https://user-images.githubusercontent.com/33670923/73288180-5fc43d80-41af-11ea-860d-60774ca613ed.png)

I don't have a strong preference between the two, just not a fan of the carets/headers being _indended._

Original mockup for reference. 

![image](https://user-images.githubusercontent.com/33670923/73288171-5cc94d00-41af-11ea-9685-c7a5a398a7a6.png)

**Comment by axoplasm** [comment]
something like this would be easy:
![image](https://user-images.githubusercontent.com/169060/73304995-264efa80-41ce-11ea-8ea5-579fd4b4d00a.png)

**Comment by jennyhavah** [comment]
@axoplasm The alignment looks good. Could we avoid boxes around the disaggregation list unless required to make a scrolling affordance obvious? That's why only Afghanistan has a box in my mockup. 

There is probably a better way than a box to make the scrolling affordance visible, that would be more visually consistent, and we can avoid boxes-inside-of-boxes altogether.

**Comment by axoplasm** [comment]
Added some left padding to simulate an indent:

![image](https://user-images.githubusercontent.com/169060/73690986-55f67a80-4686-11ea-93ae-83b5aba80d58.png)

(I have a question about a potential bug, I’ll ping the development channel with it)

**Comment by jennyhavah** [comment]
@axoplasm Indenting looks great. As we discussed just now, let's see if we can make the bottom edge of the scrolling area more visible. You mentioned the possibility of a line or shadow effect just along the bottom, to avoid having to put a box around the whole thing:

![image](https://user-images.githubusercontent.com/33670923/73694225-7d504600-468c-11ea-9620-316741cd97e0.png)

**Comment by axoplasm** [comment]
It's easy to do something like this (where the style is applied to *all* the disaggregation lists:

![image](https://user-images.githubusercontent.com/169060/73697030-73c9dc80-4692-11ea-8adb-a4ea18768160.png)

…having that styling show up *only* when the element overflows, is a lot harder

**Comment by jennyhavah** [comment]
Just chatted with Paul and he said it could be upwards of a day to make the shadowing only appear when the list is long enough to be scrollable.

I find the shadowing useful only if it serves as a differentiator. If it shows up on all lists, not so much. However, I'm not convinced it's a big enough issue to warrant a day's worth of effort.

Let's leave as is, with no shadow effect. If we get user feedback that the lack of scrolling affordance is bothersome, we can revisit in the future. Passing the ticket as is.
