### ISSUE TITLE
Indicator setup > Deleting targets returns a 404: Not found error

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2228]
This issue is only on QA, not on Prod. To reproduce:

1. Add a new indicator.
2. Go to the Target tab and select a target frequency.
3. Click "Remove all targets" and then hit "OK" on the confirmation message.

I'm consistently getting this message:
![image](https://user-images.githubusercontent.com/33670923/74880407-01a6f800-5320-11ea-8caa-73bad8d0daf2.png)

This is consistently happening regardless of:
- Target frequency (including LoP, Midline/Endline and Event)
- Whether or not I've completed all required fields
- Whether or not I've entered numbers in the target value fields.

It doesn't happen when I delete targets for saved indicators -- regardless of whether or not a result is linked to it. Only new indicators.

Here's what I'm seeing in Developer tools:
![image](https://user-images.githubusercontent.com/33670923/74880458-213e2080-5320-11ea-8a08-a45bc37a58b5.png)

**Comment by camgnostic** [comment]
Issue caused by bad check for if this is a results form, making the error dependent on whether a results row for a different indicator was expanded when you add a new indicator (if a results row was expanded anywhere on the program page, it would think it was a results form and attempt to send away for targets, getting a 404 error.  I've changed the "is this a results form" test to be more reliable.

**Comment by jennyhavah** [comment]
Fixed. No longer seeing the 404 error when I delete targets.
