### ISSUE TITLE
Result form jogs when Pnotify is displayed.

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2297]
Under certain conditions, the result form prompt jogs down and up when modifying a result. To reproduce:

1. Open up a saved result.
2. Modify any of the disaggregations so that the disaggregated values do not add up to the total value. (This used to be forbidden but is now permitted -- we warn but do not block submission.)
3. Click "Save changes".

Here is what I'm seeing. Note how the whole result form appears to jiggle as the yellow PNotify prompt appears.

![pnotifyJog](https://user-images.githubusercontent.com/33670923/77354201-a04bbd80-6cff-11ea-96d8-497517394b95.gif)

This does NOT happen when:

1. I modify disaggregations _without_ causing a discrepancy between the disaggregated values and the total value.

2. I modify something unrelated to the values such as the result date.

**Comment by axoplasm** [comment]
When I replicate (or attempt to?) on my machine, I can notice this only happens when 

* I see the inline warning about the sum of disaggs not matching the actual (see below) **and**
* this error is produced when I click on **Save Changes** 

![image](https://user-images.githubusercontent.com/169060/77972305-d1029880-72a5-11ea-9455-066867faea42.png)

For example, I don’t see the jog when I enter values that don’t sum to the actual but then tab into another field (e.g. “Comments”), thus triggering the inline error **before** I click **Save Changes.**

So what I think is happening is actually a side effect of intended behaviors. Entering values that don’t sum to actual produces an inline error, __which causes the modal to grow by ~1 line of height.__ 

If I receive this error before I click __Save Changes__ (e.g. by tabbing into another fieldset), pnotify “knows” how big the modal is & can position the alert appropriately. (In reality: it is positioned according to the bottom left corner of the modal, however large that is.)

But if clicking “Save Changes” is what triggers the inline error message, pnotify pops up before the inline error, the modal resizes, and the pnotify message __moves with the newly sized modal.__

I think I can “fix” this by reversing the order of operations when I click “Save” but this might introduce some unusual side effects (because we do other error checking in those same operations). 

__anyway__ because these are all intended behaviors, I want to double-check that I’m not missing some other situations where the jog is happening. Lemme know if you want to do a screenshare so we can compare.

**Comment by jennyhavah** [comment]
@axoplasm I'm noticing the jog in both of the following circumstances:

1. **I add a new result** where the disaggregated values don't match the total. (For new results, we do not throw a "things don't add up" warning until you submit, so it doesn't matter whether I tab out of the cell or hit "Save changes" straightaway.)

2. **I edit a saved result** that does not yet have any disaggregation discrepancies, in such a way that I introduce a disaggregation discrepancy, AND I hit "Save changes" straightaway; I don't tab out of the cell, which triggers the in-line warning before I save.

I can't come up with any other scenarios where the jog occurs.

I'm not sure I understand what you mean by "reversing the order of operations". Currently, warnings and prompts are all appearing when and where expected. Like, I wouldn't want to start throwing warnings before you submit a result for the first time -- we intentionally avoided that noisiness. (Don't think you were suggesting this, just erring on the side of over-communication.)

**Comment by sanjuroj** [comment]
@axoplasm I think you're right about the inline error adding vertical space.  I would be careful about reversing operations though.  The rationale prompt confirmation message is dependent on what kinds of errors you have, so the errors need to be identified before the rationale prompt is triggered.  I was sort of hoping we could just ensure that the error message filled an existing space rather than inserting.

**Comment by jennyhavah** [comment]
Looks good to me. No longer seeing the form jog and warning messages are appearing as expected when adding and editing disaggregated results.
