### ISSUE TITLE
Indicators: Add --All-- option to Programs menu

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#23]
<a href="https://github.com/jennyhavah"><img src="https://avatars3.githubusercontent.com/u/33670923?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jennyhavah](https://github.com/jennyhavah)**
_Thursday Dec 14, 2017 at 04:31 GMT_
_Originally opened as https://github.com/mercycorps/mcta/issues/13_

----

**Affects:** The Programs filter menu at the top of the Indicators page.

**Problem:** 
1. Go to indicators
2. Open the _Programs_ filter menu at the top of the page.
3. Filter on a program.
4. Now try to get the full list of indicators back.
4.1. **Expected:** I can select --All-- in the _Programs_ filter menu, just like I can in the _Indicators_ menu next to it. (This is a common convention in many of the filter menus in the app.)
4.2. **Observed:** There is no --All-- option, so I have to reload the Indicators page to get the full list.

**Requested fix:** Add the --All-- option to the _Programs_ filter menu

![scrap](https://user-images.githubusercontent.com/33670923/33975629-80f6d978-e044-11e7-8eee-528e75cf3634.png)

**Comment by jennyhavah** [comment]
Validated. "All" option appears and works as expected.

![image](https://user-images.githubusercontent.com/33670923/35888639-46bf2e52-0b4d-11e8-9fde-1ea97e64ed45.png)

**Comment by sanjuroj** [comment]
@jennyhavah @mahmoodkhan This comment probably isn't directly related to this issue, but I wanted to put it somewhere.  The -- All -- option is now appearing for the Program dropdown and behaves as expected.  However, it looks like the behavior of the Program dropdown is inconsistent with that of the Indicator dropdown.  While the Program dropdown shows both of the Programs available to me, the Indicator dropdown doesn't show all of the indicators available to me (I'm not sure what it's supposed to show, so this may be appropriate).  Also, when I select a Program, the Program menu switches back to saying "Program" once the list has been filtered.  The Indicator menu retains the name of the filter that I've selected, rather than going back to "Indicator".  This all may be working as intended, I just thought I'd mention it.

**Comment by mahmoodkhan** [comment]
The validation @jennyhavah provided was prior to these latest round of changes including the cascading effect from "Program" to "indicator" and the autocomplete feature. I have removed the --All-- option because you can use the "x" on the dropdown to clearout the selection.

**Comment by sanjuroj** [comment]
Looks good, the latest changes addressed all of the points from my last comment.
