### ISSUE TITLE
Global: COVID-19 banner

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#2319]
# Issue

The MEL team would like to promote their COVID-19 guidance and resources on TolaActivity.

# Acceptance criteria

![image](https://user-images.githubusercontent.com/33670923/79607278-cfa7dd00-80a7-11ea-86a9-43ad86ea4fd5.png)

- [x] 1. The COVID-19 banner appears globally, at the top of every page.

- [x] 2. It has an "X" icon in the right corner. If I dismiss the banner, it is removed 
    - [x] …across the entire site…
    - [x] …_for that session only._ 
    - [x] Next time I login, I see it again. (We don't want to be annoying and make people dismiss it on every page. But we also don't want to assume that because someone dismisses a banner once, they have no interest in seeing this information, ever.)

- [x] 3. The banner is translated AND the links go to the translated versions of each resource.

     - [x] 3.1. The bolded text reads:

     COVID-19: Remote MERL guidance (PDF) `|` Recorded webinar
     COVID-19: Guide SERA à distance (PDF) `|` Webinaire enregistré
     COVID-19: Guía de la MERL remota (PDF) `|` Webinar grabado  

Language | Link one | Link two
------------ | ------------- | -------------
English | https://library.mercycorps.org/record/32352/files/COVID19RemoteMERL.pdf | https://drive.google.com/open?id=1x24sddNU1uY851-JW-6f43K4TRS2B96J
French | https://library.mercycorps.org/record/32636/files/COVID19RemoteMERLfr.pdf | https://drive.google.com/open?id=19CW8mfUzHfxX_E2RlMFgao-XfElHbaaR
Spanish | https://library.mercycorps.org/record/32635/files/COVID19RemoteMERLes.pdf | https://drive.google.com/open?id=1x24sddNU1uY851-JW-6f43K4TRS2B96J

## Housekeeping
* [x]  Unit test/s written wherever applicable
* [x]  i18n tags included wherever applicable
* [ ]  Functionality is accessible to people using screen readers

**Comment by axoplasm** [comment]
@jennyhavah I added some acceptance criteria for behaviors on the banner. 

@sanjuroj or @camgnostic I assume I will need to use a session variable for this? I will dig into it but haven't done this … ever? … on a Django site. If I start to spin I will hand it off.

Also: can we put the translation links in the .po file, or should I use the language variable?

**Comment by camgnostic** [comment]
I would recommend language variable because the .po file undergoes complicated updates and it'd be weird to send links to a translator, I think?
For sessions, we have the session middleware engaged, but the only place we're using it is in our language middleware (but it does give a template for session variable updating in our current setup - that said I think you were the one who wrote that piece, Paul?).   I think you'll need an endpoint to bounce an AJAX update back to the backend to update the session, too, right?

**Comment by sanjuroj** [comment]
For the translation links, I think you can do whichever you feel more comfortable with.  If you go the .po route, we'd just add the "translated" url links to the .po files ourselves, before they were sent to the translator.

**Comment by axoplasm** [comment]
ok language variable it is!

I did write the language middleware but devil if I can remember anything about it. Can either of you take the session-variable-handling part? (Crit. 2)

**Comment by camgnostic** [comment]
@jennyhavah if I click "close", do we want this to reappear again the next time I open a browser window (like, if I close the tab but then open it again) or the next time I _log in_?  Because a browser "session" and a log-in "session" aren't the same (related to cookies - think about the times when you can open Tola and be logged in still because you logged in earlier today, even if you closed your tabs) - it affects how we set up the session variable.  Thoughts?

**Comment by jennyhavah** [comment]
@camgnostic Assuming it doesn't significantly increase the level of effort, I would vote for next time you _log in._

I can imagine a situation where someone wants to have multiple windows of Tola open side by side, and it might feel odd or annoying if they thought they got rid of the banner in window 1 and then see it again i window 2.

**Comment by jennyhavah** [comment]
@camgnostic Looks like the Pipe sign with spaces on each side is missing, in between the two links.

![image](https://user-images.githubusercontent.com
/33670923/80258171-6724a700-8637-11ea-9a30-4a6bef6a545d.png)

**Comment by jennyhavah** [comment]
All looks good now!
