### ISSUE TITLE
Remove confusing Logout option from navbar Profile dropdown

### ISSUE THREAD

**Issue by kurtwall** [mercycorps/TolaActivity#46]
The navbar has a user profile dropdown that allows one to logout. Except that as along as one has an active session with Mercy Corps' SSO, such as TolaActivity session open (say, in another tab) or maybe you're still just logged into Mercy Corps gmail, the logout will not work. Instead, it returns to the Dashboard page. This is confusing behavior; I suggest removing the Logout option from the profile menu or adding help text around it.

**Comment by jennyhavah** [comment]
@mahmoodkhan Would there be any security reason to give people a way to log out of SSO entirely from the TolaData nav bar? Assuming that's even technically feasible for us to implement, which it may not be.

If not, then I agree that it's misleading to have that link there and we should remove.

**Comment by mahmoodkhan** [comment]
Since SSO is used for other apps too and I can imagine a situation where a user is logged in to multiple apps that are behind SSO and may have unsaved work in one of the apps. It is possible that a user does not realize that by logging out from Tola s/he is also logging out of the other app behind SSO and may potentially lose her/his unsaved work. So I would suggest we not log out users from SSO in Tola.

**Comment by jennyhavah** [comment]
Sounds good. Validated -- Logout link is no longer in the profile menu.
![image](https://user-images.githubusercontent.com/33670923/35888360-33d4ffde-0b4c-11e8-8bf3-af283389a757.png)

**Comment by kurtwall** [comment]
👍
