### ISSUE TITLE
Project approval flow: Problem with "start tracking your project" button and locked forms

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#477]
From Marie: After approving the PI Form, selected "start tracking your project" and got an error. Now both PI and PT forms are locked and I can’t move forward.

This sounds similar to problems raised by one or two program teams.

**Comment by sanjuroj** [comment]
The problem was with a badly formed url (one that required a pk but wasn't getting one from the page context).  The project creation and updating process should now work and the "Tracking Form" button on the project list page should now be unlocked once you've created the tracking form:

Steps to test:
1.  Create a new project
2. Approve the project
3. Click on the "Start tracking your project" on the project dashboard
4. Successfully save the Project Tracking Form, and update it if desired.

The urls that were causing the error should also be tested.  They are the "Project Dashboard" link in the breadcrumb and the project title link (just under the "Project tracking form" header), which should also go to the dashboard.

**Comment by jennyhavah** [comment]
I was able to complete the steps as described, for both short and long versions of the initiation form. I also did not have trouble accessing the project dashboard using the breadcrumbs or the link under the project title.
