### ISSUE TITLE
Exporting TvA Annual report to Excel: Error page with TolaData Demo program

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#508]
To reproduce, go to the IPTT landing page, select TolaData Demo, Annual target frequency, create the report, and attempt to export to Excel.

On production, we get the Michael Jordan error page. On Demo, it's this error page:

![image](https://user-images.githubusercontent.com/33670923/43160548-5ba3faf2-8f3a-11e8-9526-66d9377ab42e.png)

So far, we've only encountered this issue with TolaData Demo, on both Production and Demo. We can export other target frequencies for the same program, and Annual reports for other programs.

**Comment by sanjuroj** [comment]
The specific problem that precipitated the filing of this issue was an indicator with an LOP frequency that had a target value of 0 but results with a value of >0.  In the IPTT report (i.e. the web page), the value in the "percent met" column is N/A (to account for the division by zero error).  But when this value is exported to Excel, an error occurs.  The exact cause of the error is unknown (figuring it out would require a bit more research).

There were two fixes to make this work.  Exporting the value with an encoding (UTF-8) resulted in the Excel export functioning as expected with the "N/A" value visible on the spreadsheet.  There's also a fallback of not printing anything if the value-setting operation fails in a certain way.  These fixes address the original issue of dividing by zero, but should also handle some (but probably not all) other situations where an unexpected value is passed to the Excel exporter.
