### ISSUE TITLE
Associate CollectedData records upon changing of target frequency

### ISSUE THREAD

**Issue by mahmoodkhan** [mercycorps/TolaActivity#53]
When a user removes all existing targets all of the associated CollectedData records get disassociated as a result. However, when a user specifies a new target_frequency, creates new targets, and save the indicator form, then the system should automatically re-associate as many of the CollectedData records as possible by using the periodic_targets' start and end dates as a range for the date_collected field of the CollectedData records.

Acceptance criteria:
Make sure that CollectedData records are dis-associated when all periodic targets are removed
Make sure that CollectedData records are re-associated when new targets for a new target_frequency are generated and saved with valid values.

**Comment by jennyhavah** [comment]
The functionality looks good! This story brought up a usability issue I'd like to address. I'm happy to open a new ticket if needed, but am hoping it's trivial enough to take care of here.

I'm finding it adds a lot of cognitive load to have the date formatting be essentially reversed between the Date collected field and the Measure against target field. I have to make a lot of little mental adjustments to reconcile the two fields

![image](https://user-images.githubusercontent.com/33670923/35200458-9da5954e-fec3-11e7-9dd2-7d2824436799.png)

Can you format the "Date collected" form field the same way we do the period names? I.e. Jan 12, 2017 instead of 2017-12-01? We can still allow users to enter the date in whatever method is most comfortable, including 2017-12-01. But can we automatically convert that to the format that we're using everywhere else? Ideally upon tabbing out of the field, but if that's hard to do, at least upon save?

**Comment by jennyhavah** [comment]
![image](https://user-images.githubusercontent.com/33670923/35413665-06456cb4-01d5-11e8-988d-81cfae352906.png)

The Measure against target field is not accepting the first and last days of each period as valid.
