### ISSUE TITLE
Indicator Target Period names not translated

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#598]
Edit an Indicator page > Target tab > Titles of the target frequency, e.g. Quarter 1, Quarter 2

![image](https://user-images.githubusercontent.com/169060/45378168-95b05400-b5b1-11e8-9c42-82264ea070e7.png)

**Comment by axoplasm** [comment]
Target period names are programmatically generated but stored directly in the DB (& thus non translatable). e.g. If you created your target periods for an indicator while your language was Spanish those names __for those targets for that indicator__ will forever be in Spanish regardless of how you switch your language preference.

![image](https://user-images.githubusercontent.com/169060/45380465-9f3cba80-b5b7-11e8-8dcd-8278d562569a.png)

vs.

![image](https://user-images.githubusercontent.com/169060/45380575-e460ec80-b5b7-11e8-9617-e6e06b56bcbd.png)

**Comment by sanjuroj** [comment]
The proper solution to this could be somewhat involved. It would require something like storing the sequence number in the db rather than the label and building the label in the view or the template. The other hackier option would be to regex the period number off the back of the label and then rebuild the label. That might be a reasonable interim solution.

**Comment by jennyhavah** [comment]
@sanjuroj @axoplasm Can this ticket be closed, now that we've done #744?

**Comment by sanjuroj** [comment]
yep
