### ISSUE TITLE
Language translation: Switching between languages, I see all three languages

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#637]
This happened on production:

1. I switched my language from English to Spanish.
2. I went to the indicators page and opened up the results form to try some stuff.
3. I went back to my profile and switched from Spanish to French. Saved multiple times -- the form says it's now French.
4. I went back to the Indicators page.

Here's what I see:
1. The navigation and Program containers are French
2. The column headers of the results tables are French
3. The target period dates are in a mix of Spanish and English

Here's what I saw after switching from Spanish to French. 
![image](https://user-images.githubusercontent.com/33670923/46172706-082f5e00-c259-11e8-9f10-0d2c12353ae7.png)

Here's what I saw after switching from French to English. The difference here is that the program container labels are in English instead of French. But I still see Spanish years in the first open indicator row.
![image](https://user-images.githubusercontent.com/33670923/46172813-4e84bd00-c259-11e8-98f3-abdee628a9d0.png)

**Comment by sanjuroj** [comment]
This is a design issue that's experienced as a bug.  In the examples above, everything except the periodic target labels (e.g. "Year 1" and "AÑO 1") are being translated or localized appropriately.  The periodic target labels are generated in whatever language the user currently has set and are saved in the database.  Because we've made a general decision not to translate anything coming out of the database, we are not translating the labels.  

Depending on how the labels are handled in the Django templates, it may be possible to add translation tags to the labels.  Another option might be modify what we store in the database (e.g. we could just store the sequence number and "calculate" the text part of the label from the target frequency type.  

This is not something that most users are likely to face, they will most likely be using a single language.  But it would be nice to fix it to avoid confusion, especially during training.

**Comment by jennyhavah** [comment]
@sanjuroj Can this be closed now that we've done #744?

**Comment by sanjuroj** [comment]
Yep
