### ISSUE TITLE
Create an indicator import script

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#696]
Country indicators are currently put in by hand, even if they are already in a digestible Excel format.  It would save some work for the trainers if we had a command line script that could be used to upload indicators.

**Comment by jennyhavah** [comment]
@sanjuroj This ticket is pretty old, and I'm wondering if we still need it. Since then, we've shifted our focus away from "let's assume people will keep building their Indicator Plans in Excel" to, "How can we make it more efficient to manually enter indicator info into Tola, with a more tabular, Excel-like interface?" Then as they make tweaks to individual indicators, they can export the Indicator Plan that will always be the most up to date... As opposed to updating their Excel spreadsheet and re-importing it.

Would it be okay to close this ticket?

**Comment by sanjuroj** [comment]
@jennyhavah Makes sense to me.
