### ISSUE TITLE
Investigate pros and cons of available UI frameworks

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#83]
Before we update to the latest version of Bootstrap, let's do a quick comparison analysis of several of the most widely used UI frameworks and make sure Bootstrap is the best solution for us. 

These are the frameworks to compare:
1. Bootstrap
2. Foundation
3. Any others you feel are worth considering: UIKit, Bulma, etc.

Requested deliverable: Informal written or verbal summary of findings and recommendations.

**Some articles I found helpful for background**
I looked for comparisons of the latest versions of Bootstrap and Foundation.

Talks about customize-ability and grid systems: [Bootstrap vs. Foundation: Which Framework Is Right for You?](https://www.upwork.com/hiring/development/bootstrap-vs-foundation-which-framework-is-right-for-you/)

These two articles focus on grid and navigation elements which are particularly relevant to the upcoming release with complex tables and (I'm hoping) slide-out configuration panel:
- [Part 1: Bootstrap 4 vs Foundation 6.4 — The Grid](https://codeburst.io/part-1-bootstrap-4-vs-foundation-6-4-the-grid-8c02747f14fb) 
- [Part 2: Bootstrap 4 vs Foundation 6.4 — Responsive Navigation & Containers](https://codeburst.io/part-2-bootstrap-4-vs-foundation-6-4-responsive-navigation-containers-f691cff8f06e)

**Comment by mahmoodkhan** [comment]
https://www.codementor.io/codementorteam/bootstrap-3-vs-foundation-5-which-front-end-framework-should-you-use-8s90mhsgn

https://www.thebalance.com/bootstrap-or-foundation-2071893

**Comment by mahmoodkhan** [comment]
Both frameworks (Bootstrap and Foundation) are open-source and great UI framework. Bootstrap is a little more like a cookie-cutter approach and provided for high-level functionality/UI features. In contrast, Foundation is a low-level and allows for greater customization, which means it would take slightly longer to achieve similar tasks because you have to more of the work yourself.

For me the benefit of Bootstrap is its much larger community behind it. It has more than 120,000 stars on Github compared to Foundations' 26000 stars and over 80000 questions tagged with bootstrap in stack overflow 800 questions tagged with foundation.

The benefits of the larger community are more information, more tutorials, and more resources available on the Internet as well as more plugins and potentially more integrations / playing nice with other frameworks.

Finally, switching UI framework could easily add at least 2 weeks time to implementation. So my suggestion is to stay with Bootstrap and possibly upgrade to Bootstrap ver.4

**Comment by jennyhavah** [comment]
Something else Mahmood mentioned to me as a downside to Foundation is that it's customizability increases development time for many features that we might implement. Given our ambitious roadmap and short time frame, it doesn't make sense to add more work to get whatever additional customization options Foundation may offer.

I am moving this spike to Done and will send a message about it on Slack.
