### ISSUE TITLE
Program Documents page should show program name

### ISSUE THREAD

**Issue by axoplasm** [mercycorps/TolaActivity#858]
@esinn noted this in #574. See comment https://github.com/mercycorps/TolaActivity/issues/574#issuecomment-442625662

**Comment by esinn** [comment]
Should this be a GhostPepper candidate? @jennyhavah @axoplasm

**Comment by jennyhavah** [comment]
When I click "View program documents", I see the program name underneath the page title. It looks like this:
![image](https://user-images.githubusercontent.com/33670923/49313506-5270cd80-f49c-11e8-955b-2e34081348f9.png)

@axoplasm Small detail... The colon after "Documents" is reads to me like a broken breadcrumb. If we had kept it all one line, the colon would have been a helpful separator. But since we decided to put the program on its own line -- which looks great -- I'd take out the colon.

**Comment by jennyhavah** [comment]
Colon is gone!
