### ISSUE TITLE
Result form: Restrict the entry of results with a results date after today

### ISSUE THREAD

**Issue by jennyhavah** [mercycorps/TolaActivity#893]
# Issue
If I am permitted to enter a result for a target period in the future, then my % met numbers will sometimes come across as miscalculated in both the results table and the IPTT. This is because our Mangosteen queries only include results up to and including the current target period, for all time-aware target frequencies.

We want to nip this problem in the bud by restricting the ability to enter results with a date after today. 

**Affects:** Result form

## Acceptance criteria

- [x] 1. Whether I am using the calendar picker or manually entering a date, I am only permitted a date up to and including today.
- [x] 2. When the entire program period ends, I can add a result to any date from the start date to the end date.
- [x] 3. If today's date is prior to the program start date, I can't add results.
- [x] 4. The system immediately validates my entry, prior to submitting.
     - [x] 4.1. If the date is later than today, I get a validation warning: Please select a date between [first day of program period] and [today's date].
     - [x] 4.2. If today's date is prior to the program start date, I get a validation warning: You can begin entering results on [program start date], the program start date.
     - [x] 4.3. Date formats in the validation message are localized.

## Testing:
- [x] Run through all fields that accept input, ensure required fields react to improper/missing text & info appropriately
- [x] Ensure built to spec, acceptance criteria is met
- [x] Run through acceptance criteria requirements multiple times.
- [x] (Validate input Fields) Attempt to save results with incorrect strings, numbers, special characters, etc.

## Estimated Test Time (Acceptance): 
1 - 2 hours

**Comment by KennyMonster** [comment]
@jennyhavah There's an edge case to consider here, namely timezones and the international date line, which can result in the user being in a different day than the server.

It turns out there is actually a time period where 3 different days exist at the same time: https://www.timeanddate.com/time/dateline.html

Anyhow, when it comes to validation, the decision of what time zone to use to calculate the current date must be made. Do you use the server's time zone (pacific time), the users time (this can literally be anything depending on what their computer is set to), or UTC?

To given an example, the server may think is 12/31/18, but the user being ahead in time might be in a timezone where it's 1/1/19 locally. If the program date starts on 1/1/19, entering a date locally and comparing it would pass validation, but when the request is sent to the server, the server side validation would compare to local time which is still 12/31/18, thus failing validation.

**Comment by jennyhavah** [comment]
It seems not so edgy at all, in that many of our users are in different time zones. This reminds me of issues we dealt with in Winterhawks, where time zone differences were leading to unexpected results when it came to target period generation, and possibly the program period modal as well.

Our general approach -- as I recall -- is to base "current date" and validation of such, on what the user's own computer is set to. But I'd like to ask @sanjuroj to validate this.

**Comment by KennyMonster** [comment]
Because in this case we do need to do date comparisons on both the client and server, there needs to be a way to sync up the users timezone to the server so the client and server can can compare in the same timezone. I think a user pref is the right way to do that sync up, but another possibility is to use JS to pull the timezone from the browser and send that as part of the form submission. The server could then use that timezone for the lifetime of the form submission request.

**Comment by jennyhavah** [comment]
For posterity:

**Comment by RickieT** [comment]
**Deployment Verification**

- [x] Confirmed “Ready for Deploy” status


- [x] 1. Whether I am using the calendar picker or manually entering a date, I am only permitted a date up to and including today.
- [x] 2. When the entire program period ends, I can add a result to any date from the start date to the end date.
- [x] 3. If today's date is prior to the program start date, I can't add results.
- [x] 4. The system immediately validates my entry, prior to submitting.
     - [x] 4.1. If the date is later than today, I get a validation warning: Please select a date between [first day of program period] and [today's date].
     - [x] 4.2. If today's date is prior to the program start date, I get a validation warning: You can begin entering results on [program start date], the program start date.
     - [x] 4.3. Date formats in the validation message are localized.

## Testing:
- [x] Run through all fields that accept input, ensure required fields react to improper/missing text & info appropriately
- [x] Ensure built to spec, acceptance criteria is met
- [x] Run through acceptance criteria requirements multiple times.
- [x] (Validate input Fields) Attempt to save results with incorrect strings, numbers, special characters, etc.
