### ISSUE TITLE
Unescaped translated string in JS breaking the JS

### ISSUE THREAD

**Issue by sanjuroj** [mercycorps/TolaActivity#914]
validation_msgs['target'] = '{% trans "Please complete all required fields in the Targets tab." %}'; in indicator_form_common_js.html needs escapejs filter.

**Comment by sanjuroj** [comment]
This can be seen when loading a program page in French.

**Comment by hannalcamp** [comment]
@sanjuroj I changed my language to French and brought up a number of program pages where all the targets are not complete, as well as created a test indicator and deliberately didn't fill out the targets tabs to see if validation worked. Everything seems fine, but I'm not sure I'm testing exactly what I'm supposed to?

**Comment by sanjuroj** [comment]
@hannalcamp Sorry, I should provided better testing instructions.  I found this when I navigated to a program page and tried to expand the indicators to show the results table.  Unfortunately, I didn't write down which program I was trying (it might have been in Jordan?)

The message that was modified was "Please complete all required fields in the Targets tab", so if you can find an create an indicator that would generate that message, switch to French and try to open the results table, that should be a good test.

**Comment by hannalcamp** [comment]
OK, I'm not getting the errors so I think that's fixed. Two things to note, though:
1. In the indicator tables, "Missing targets" is not translated. (See TolaData Test for examples)
2. It looks like "Please complete all required fields in the Performance tab" has not yet been translated either. This screenshot shows what happens when I try to save an indicator with only a name (no level or targets.)

![screen shot 2018-12-07 at 10 01 55 am](https://user-images.githubusercontent.com/38020496/49661776-3ecae700-fa07-11e8-9786-8b9fb05aee4e.png)

**Comment by sanjuroj** [comment]
@hannalcamp Thanks for letting me know about the missed translations.  I'll make sure they get translated before we release.
